source $AZIM_HOME/modules/azim/hooks.zsh
source $AZIM_HOME/modules/azim/completion.zsh
source $AZIM_HOME/modules/azim/directories.zsh
source $AZIM_HOME/modules/azim/grep.zsh
source $AZIM_HOME/modules/azim/history.zsh
source $AZIM_HOME/modules/azim/key-bindings.zsh
source $AZIM_HOME/modules/azim/theme-appearence.zsh
source $AZIM_HOME/modules/azim/aliases.zsh
source $AZIM_HOME/modules/azim/dev.zsh
